# Site settings
title: Maratona GO
description: >
  Projeto para divulgação de informação sobre a Maratona de Programação
  e compartilhamento de conhecimento sobre Competitive Programming.
baseurl: "" # the subpath of your site
url: "https://paulocezar.github.io/maratonago" # the base hostname & protocol for your site

# User settings
#username:
#user_description:
#email:
#twitter_username:
#gplus_username:
github_username: maratonago
disqus_username: maratonago

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
highlighter: rouge
permalink: /:title

plugins:
  - jekyll-gist
whitelist:
  - jekyll-gist

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Inicio
    url: /
  - title: Tags
    url: /tags
  - title: Materiais
    url: /materiais
  - title: Sobre
    url: /sobre

include: ['_pages', '_assets']
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
